import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderTop from "@/components/HeaderTop";
import Banner from "@/components/MainPage";
import MainPage from "@/components/MainPage";
import AboutSection from "@/components/AboutSection";
import CategorySection from "@/components/CategorySection";
import ServicesSection from "@/components/ServicesSection";
import ColoursSection from "@/components/ColoursSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderTop />
        <MainPage />
        <AboutSection />
        <CategorySection />
        <ServicesSection />
        <ColoursSection />
        {children}</body>
    </html>
  );
}
